# Copyright © 2024 The µcad authors <info@ucad.xyz>
# SPDX-License-Identifier: AGPL-3.0-or-later

[workspace]
default-members = [
    "core",
    "export",
    "lang",
    "std",
    "tests",
    "builtin",
    "tools/cli",
]

members = ["core", "export", "lang", "std", "tests", "builtin", "tools/cli"]
resolver = "2"

[workspace.package]
authors = [
    "Michael Winkelmann (michael@winkelmann.site)",
    "Patrick Hoffmann (p.hoffmann@berlin.de)",
]

version = "0.1.0"
edition = "2021"
rust-version = "1.79"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
microcad-core = { path = "core" }
microcad-export = { path = "export" }
microcad-lang = { path = "lang" }
microcad-std = { path = "std" }
microcad-builtin-proc-macro = { path = "builtin" }
microcad-cli = { path = "tools/cli" }
