[workspace]
default-members = [
    "core",
    "export",
    "lang",
    "render",
    "std",
    "tests",
    "builtin",
    "tools/cli",
]

members = [
    "core",
    "export",
    "lang",
    "render",
    "std",
    "tests",
    "builtin",
    "thirdparty/manifold-rs",
    "tools/cli",
]
resolver = "2"

[workspace.package]
authors = [
    "Michael Winkelmann (michael@winkelmann.site)",
    "Patrick Hoffmann (p.hoffmann@berlin.de)",
]

version = "0.1.0"
edition = "2021"
rust-version = "1.73"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
