use std::ops::*;
use std::geo2d::*;
use std::math::*;

part foot_pad(
    height = 45mm,
    base = (x = 155mm, y = 101mm, z = 18mm),
    slot = (x = 8mm, y = 13mm),
    center_hole = (d_inner = 42mm, d_outer = 55mm),
    corner_hole = (d_lower = 14mm, d_upper = 22mm),
    corner_radius = 15mm,
) {
    s = (x = base.x / 2 - corner_radius, y = base.y / 2 - corner_radius);
    hole_pos = (x = [-1,1]*s.x, y = [-1,1]*s.y);
    r = corner_radius;
    
    base_lower = Circle(r, c = hole_pos)
        .hull()
        .extrude(12mm);

    base_upper_height = slot.x;
    base_lower_height = base.z - base_upper_height;

    base_upper = {
        top_left = (x = -s.x, y = s.y);
        top_right = (x = s.x, y = s.y);
        bottom_left = (x = -s.x, y = -s.y);
        bottom_right = (x = s.x, y = -s.y);
        (Circle(r, c = [top_left, bottom_right]).hull() | Circle(r, c = [top_right, bottom_left]).hull());
    }
    .extrude(base_upper_height)
    .translate(z = base_lower_height);
    
    center = {
        (Circle(d = center_hole.d_outer) - Circle(d = center_hole.inner_d))
            .extrude(height);
        
        rect(height = slot.x, width = center_hole.outer_d)
            .extrude(slot.y)
            .translate(z = height - slot.y);
        
    }.difference();

    holes = {
        Circle(d = corner_hole.lower_d, c = hole_pos)
            .extrude(height = base_lower_height);
        Circle(d = corner_hole.upper_d, c = hole_pos)
            .extrude(height = base.z * 2)
            .translate(z = base_lower_height);
        Circle(d = center_hole.inner_d)
            .extrude(height);
    }.union();

    base_lower | base_upper | center - holes;
}

foot_pad();