[package]
name = "csg-parser"
description = "A parser for the CSG language"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
pest = "2.7"
pest_derive = "2.7"

[build-dependencies]
pest_test = { path = "pest_test" }
