[package]
name = "microcad-render"
description = "µCAD renderers"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
log = "0.4"
rctree = "0.6"
geo = "0.28"
cgmath = "0.18"

microcad-core = { path = "../core" }
