[package]
name = "microcad-lsp"
description = "LSP backend for microcad"
documentation = "https://docs.rs/microcad-lsp"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
keywords = ["microcad", "lsp", "language"]
categories = ["Programming Languages"]

[dependencies]
log = "0.4"
env_logger = "0.11.8"
tower-lsp = "0.20"
tokio = { version = "1.48", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.18"

[[bin]]
name = "microcad-lsp-client"
path = "src/client.rs"

[[bin]]
name = "microcad-lsp"
path = "src/server.rs"
