[package]
name = "microcad-builtin-proc-macro"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
syn = { version = "2.0.75", features = ["full", "fold"] }
quote = "1.0.8"
