# Copyright © 2024-2025 The µcad authors <info@ucad.xyz>
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "microcad"
version = "0.2.1"
description = "µcad Command Line Interface"
documentation = "https://docs.rs/microcad"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
default-run = "microcad"

[[bin]]
name = "microcad"
path = "main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
env_logger = "0.11"
lazy_static = "1.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
toml = "0.9"
notify = "8"
home = "0.5.11"

microcad-lang = { workspace = true }
microcad-core = { workspace = true }
microcad-builtin = { workspace = true }
microcad-export = { workspace = true }

[build-dependencies]
walkdir = "2"
rustfmt-wrapper = "0.2"
anyhow = "1.0"

[lints.rust]
missing_docs = "warn"

[lints.clippy]
unwrap_used = "warn"
