[package]
name = "microcad-std"
description = "µCAD Standard Library"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
pest = "2.7"
pest_derive = "2.7"
log = "0.4"
rctree = "0.6.0"
lazy_static = "1.5"
thiserror = "1.0"
cgmath = "0.18"
geo = "0.28"

microcad-core = { path = "../core" }
microcad-parser = { path = "../parser" }
microcad-render = { path = "../render" }
microcad-builtin-proc-macro = { path = "../builtin" }

[features]
default = ["geo3d"]
geo3d = []
