[package]
name = "csg-tree"
description = "A tree for the CSG language"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
log = "0.4"
rctree = "0.6"
geo = "0.28"

csg-parser = { path = "../parser" }
