name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y ninja-build
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Build
      run: cargo build --verbose
    - name: Run clippy
      run: cargo clippy --verbose

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y ninja-build
      run: wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb
      run: sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1.3
      with:
        version: '0.15.0'
        args: '-- --test-threads 1'
