name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install ninja-build
      run: sudo apt-get install -y ninja-build
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Build
      run: cargo build --verbose
    - name: Run clippy
      run: cargo clippy --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y ninja-build
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Run tests
      run: cargo test --verbose

  test-links:
    runs-on: ubuntu-latest

    steps:
    - name: Install lychee
      run: cargo install lychee
    - uses: actions/checkout@v4
    - uses: lycheeverse/lychee-action@v2.2.0
    - name: Test Links
      run: lychee --exclude-path target --exclude-path thirdparty .
    